app:
  name: transport
jwt:
  secret: ${JWT_SECRET:my_secret_key_for_jwt_hmac_sha256_32_chars}
  expires_in: ${JWT_EXPIRES_IN:3600}
spring:
  profiles:
    default: local
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml


---
# Configuration locale (H2)
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: admin
    password: admin
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    user:
      name: admin
      password: admin
server:
  port: 8080
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.diginamic.groupe1.transport.security.JWTFilter: DEBUG
openroute:
  api:
    key: 5b3ce3597851110001cf62484557f337ce7f49abbc68d34faabbd9e0

---
# Configuration production
#spring:
#  config:
#    activate:
#      on-profile: prod
#  datasource:
#    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
#    username: ${DATABASE_USER}
#    password: ${DATABASE_PASSWORD}
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    hibernate:
#      ddl-auto: none
#---
# Configuration locale (H2)

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mariadb://82.165.152.149:3307/2024-D02-G3
    username: "main3"
    password: "{P_Z6e3y"
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
          implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        properties:
          hibernate:
            globally_quoted_identifiers: true
            globally_quoted_identifiers_skip_column_definitions: true
  security:
    user:
      name: admin
      password: admin
server:
  port: 8080
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.diginamic.groupe1.transport.security.JWTFilter: DEBUG
openroute:
  api:
    key: 5b3ce3597851110001cf62484557f337ce7f49abbc68d34faabbd9e0


---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mariadb://82.165.152.149:3307/2024-D02-G3
    username: "main3"
    password: "{P_Z6e3y"
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
          implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        properties:
          hibernate:
            globally_quoted_identifiers: true
            globally_quoted_identifiers_skip_column_definitions: true
  security:
    user:
      name: admin
      password: admin
server:
  port: 8080
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.diginamic.groupe1.transport.security.JWTFilter: DEBUG
openroute:
  api:
    key: 5b3ce3597851110001cf62484557f337ce7f49abbc68d34faabbd9e0

